version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      minor-and-patch:
        update-types:
          - 'patch'
          - 'minor'
      eslint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint*'
      i18next:
        patterns:
          - 'i18next*'
          - 'react-i18next'
      react:
        patterns:
          - '@types/react'
          - '@types/react-dom'
          - 'react'
          - 'react-dom'
      react-helmet:
        patterns:
          - '@types/react-helmet'
          - 'react-helmet'
      react-query:
        patterns:
          - '@tanstack/react-query*'
      stylelint:
        patterns:
          - 'stylelint*'
      vite:
        patterns:
          - '@vitejs*'
          - 'vite'
